{
  "services": [
    {
      "type": "web",
      "name": "hungry-bird-api",
      "runtime": "python",
      "rootDir": "backend",
      "buildCommand": "pip install -r requirements.txt",
      "startCommand": "gunicorn run:app",
      "envVars": [
        {
          "key": "SECRET_KEY",
          "generateValue": true
        },
        {
          "key": "DATABASE_URL",
          "value": "sqlite:///hungrybird.db"
        },
        {
          "key": "GOOGLE_MAPS_API_KEY",
          "sync": false
        },
        {
          "key": "PYTHON_VERSION",
          "value": "3.11.0"
        }
      ]
    }
  ]
}
