"""add phone and otp

Revision ID: 238e2095fd3e
Revises: bb58511a3868
Create Date: 2026-07-07 15:59:43.796923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238e2095fd3e'
down_revision = 'bb58511a3868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('new_name', sa.String(length=100), nullable=True),
    sa.Column('new_email', sa.String(length=150), nullable=True),
    sa.Column('new_phone', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
