"""add google photo fields

Revision ID: 26fa14a56562
Revises: cb5dcbc3c9d3
Create Date: 2025-11-22 22:44:39.079455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fa14a56562'
down_revision = 'cb5dcbc3c9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('photo_reference', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('photo_reference')
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###
