"""Add rating to VendorSubmission

Revision ID: a5696cce7074
Revises: 738759359dd1
Create Date: 2026-07-04 16:38:02.592348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5696cce7074'
down_revision = '738759359dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_submissions', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
