"""add push token

Revision ID: a59de6216da0
Revises: 238e2095fd3e
Create Date: 2026-07-07 16:45:06.519829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59de6216da0'
down_revision = '238e2095fd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')
        batch_op.drop_column('push_token')

    # ### end Alembic commands ###
