"""Add ReelSubmission

Revision ID: bb58511a3868
Revises: d3f9a1b2c4e5
Create Date: 2026-07-06 16:29:34.803160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb58511a3868'
down_revision = 'd3f9a1b2c4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('video_filename', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reel_submissions')
    # ### end Alembic commands ###
