"""Add text reviews and site reviews

Revision ID: c769fb4ac232
Revises: bf2bb1a38ef5
Create Date: 2026-07-02 11:32:52.561215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c769fb4ac232'
down_revision = 'bf2bb1a38ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('rating_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('author_name')
        batch_op.drop_column('review_text')

    op.drop_table('site_reviews')
    # ### end Alembic commands ###
