"""add vendor detail fields (description, specialty_dish, opening_hours)

Revision ID: d3f9a1b2c4e5
Revises: 7ef37b5829ca
Create Date: 2026-07-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f9a1b2c4e5'
down_revision = '7ef37b5829ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specialty_dish', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('opening_hours', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('specialty_dish')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
